-- LSP server setup is now handled by Mason via conf/mason.lua.
-- mason-lspconfig's handlers() automatically call lspconfig[server].setup()
-- for every server installed through :Mason, so nothing is needed here.
